CFLAGS  ?= -g -O0 -Wall -Werror -fPIC $(OPTS) $(INCLUDE) $(DEFINES) -arch x86_64 -mmacosx-version-min=10.10
LDFLAGS ?= -lpthread -ldl -lm -lc++ -L. -arch x86_64 -mmacosx-version-min=10.10

OBJ			= bin/osx
EXECUTABLE		= bin/squeeze2hue-osx-multi
EXECUTABLE_STATIC	= bin/squeeze2hue-osx-multi-static

include Makefile

