CC	= gcc
CFLAGS  = -Wall -fPIC -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS = -s -lpthread -lm -lsocket -lnsl -L.
#LDFLAGS = -s -lpthread -lcrypto -ldl -lm -lrt -lsocket -lnsl -lz -L.
DEFINES = -D__EXTENSIONS__ -D_POSIX_PTHREAD_SEMANTICS -D_REENTRANT

OBJ			= bin/sunos
EXECUTABLE 		= bin/squeeze2hue-i86pc-solaris
EXECUTABLE_STATIC	= bin/squeeze2hue-i86pc-solaris-static

include Makefile

